WITH TRIPS AS (

    select 
    RIDE_ID,
    RIDEABLE_TYPE,
    DATEADD(YEAR,-1,DATE(TO_TIMESTAMP(STARTED_AT))) as TRIP_DATE,
    START_STATIO_ID as START_STATION_ID,
    END_STATION_ID,
    MEMBER_CSUAL as MEMBER_CASUAL,
    TIMESTAMPDIFF(second,TO_TIMESTAMP(STARTED_AT),TO_TIMESTAMP(ENDED_AT)) as TRIP_DURATION_SECOND,
    
    from {{ source('demo', 'bike') }}
)

select *
from TRIPS